# permissions for end users to edit deploymentscales.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: deployment-scale-operator
    app.kubernetes.io/managed-by: kustomize
  name: deploymentscale-editor-role
rules:
- apiGroups:
  - operator.codehorse.com
  resources:
  - deploymentscales
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.codehorse.com
  resources:
  - deploymentscales/status
  verbs:
  - get
