apiVersion: operator.codehorse.com/v1beta1
kind: DeploymentScale
metadata:
  labels:
    app.kubernetes.io/name: deployment-scale-operator
    app.kubernetes.io/managed-by: kustomize
  name: deploymentscale-sample
spec:
  active: true
  startTime: "11:15"
  endTime: "11:20"
  period: 1
  replicas: 2
  deployments:
    - name: test-deploy-1
      namespace: default
      replicas: 1
    - name: test-deploy-2
      namespace: test
      replicas: 1
