apiVersion: operator.codehorse.com/v1beta1
kind: DeploymentScale
metadata:
  labels:
    app.kubernetes.io/name: deployment-scale-operator
    app.kubernetes.io/managed-by: kustomize
  name: deploymentscale-sample
spec:
  # TODO(user): Add fields here
